installCRDs: false  # bạn cài CRDs via --set crds.enabled=true trong Makefile
prometheus:
  enabled: false

# Khi cần Let's Encrypt ở local (DNS-01/HTTP-01), tạo ClusterIssuer riêng:
# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-staging
# spec:
#   acme:
#     server: https://acme-staging-v02.api.letsencrypt.org/directory
#     email: you@example.com
#     privateKeySecretRef:
#       name: acme-account-key
#     solvers:
#       - http01:
#           ingress:
#             class: kong
