# === Harbor values.yaml (Cấu hình công khai duy nhất và đúng đắn) ===

# Phải là URL công khai, có HTTPS
externalURL: https://harbor.snapnbuy.net

harborAdminPassword: "YourStrongPasswordHere!" # Nhớ đổi password mạnh

expose:
  type: ingress
  # BẬT TLS LÊN để sử dụng HTTPS
  tls:
    enabled: true
    certSource: secret
    secret:
      # Tên Secret mà cert-manager sẽ tạo ra để lưu certificate
      secretName: harbor-tls-cert
  ingress:
    className: kong
    annotations:
      # Annotation để cert-manager biết cần dùng issuer nào
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      # kubernetes.io/ingress.class: kong
      konghq.com/strip-path: "false"
      konghq.com/proxy-read-timeout: "3600"
      konghq.com/proxy-send-timeout: "3600"
    hosts:
      # Host công khai duy nhất
      core: harbor.snapnbuy.net

# Bật/tắt các thành phần khác tùy nhu cầu
trivy:
  enabled: true
persistence:
  enabled: true # Nên bật cho môi trường thực tế

# Service types (để nguyên ClusterIP; vào qua Ingress)
portal:
  service:
    type: ClusterIP
core:
  service:
    type: ClusterIP
registry:
  service:
    type: ClusterIP
database:
  internal:
    service:
      type: ClusterIP
redis:
  internal:
    service:
      type: ClusterIP
